CREATE TABLE IF NOT EXISTS mango_user(
    pk BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(320) NOT NULL,
    password varchar(60) NOT NULL,
    role ENUM('ADMIN', 'SUBMITTER', 'MANAGER', 'SPECIALIST', 'NONE') NOT NULL,
    PRIMARY KEY (pk),
    UNIQUE KEY email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;